title: RHUL CS Cake Talks
domain: rhul-cs-cake-talks.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://rhul-cs-cake-talks.github.io # the base hostname and protocol for your site, e.g. http://example.com
email: chris.purdy.2023@live.rhul.ac.uk

term: Spring 26

exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - misc

collections:
  spring_26:
    order: 1
    name: "Spring 2026"
  winter_25:
    order: 2
    name: "Winter 2025"

collections_dir: seminars

# plugins:
#   - jekyll-autoprefixer

# autoprefixer:
#   browsers:
#     - last 4 versions

